FROM mpsamurai/neochi:raspbian-python38

COPY qemu-arm-static /usr/bin/qemu-arm-static

WORKDIR /tmp
RUN apt-get update && \
    apt-get -y upgrade && \
    pip3 install --no-cache-dir wheel numpy && \
    wget -O opencv.zip https://github.com/opencv/opencv/archive/3.4.8.zip && \
    wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/3.4.8.zip && \
    unzip opencv.zip && \
    unzip opencv_contrib.zip && \
    mv opencv-3.4.8 opencv && \
    mv opencv_contrib-3.4.8 opencv_contrib && \
    rm opencv.zip opencv_contrib.zip && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D INSTALL_PYTHON_EXAMPLES=OFF \
        -D INSTALL_C_EXAMPLES=OFF \
        -D OPENCV_ENABLE_NONFREE=OFF \
        -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib/modules \
        -D PYTHON2_EXECUTABLE=/usr/bin/python \
        -D PYTHON_EXECUTABLE=/usr/local/bin/python3 \
        -D BUILD_EXAMPLES=OFF opencv && \
    make -j${n_proc} && make install && ldconfig && \
    #ln -s /usr/local/python/cv2/python-3.8/cv2.cpython-38m-arm-linux-gnueabihf.so /usr/local/lib/python/cv2/python-3.8/cv2.so && \
    rm -Rf /tmp/* && \
    apt-get autoclean
