version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    network_mode: "host"
  neochi:
    image: mpsamurai/neochi:20191201-raspbian
    command: ["python3", "scripts/brain/predict.py"]
    volumes:
      - ./uploads:/uploads
      - ./data:/data
      - ./models:/models
    depends_on:
      - redis
    network_mode: "host"