FROM balenalib/rpi-raspbian:stretch

COPY qemu-arm-static /usr/bin/qemu-arm-static

WORKDIR /tmp
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y \
        git \
        build-essential cmake unzip pkg-config \
        libjpeg-dev libpng-dev libtiff-dev \
        libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
        libxvidcore-dev libx264-dev \
        libgtk-3-dev libatlas-base-dev gfortran \
        libffi-dev libssl-dev openssl \
        wget && \
    wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz && \
    tar zxvf Python-3.8.0.tgz && \
    cd Python-3.8.0 && \
    ./configure && \
    make -j${n_proc} && \
    make install && \
    cd .. && \
    rm -Rf Python-3.8.0 Python-3.8.0.tgz && \
    pip3 install --upgrade --no-cache-dir pip