version: '3'
services:
  neochi-package-test:
    build:
      context: .
    volumes:
      - ./uploads:/uploads
      - ./data:/data
      - ./models:/models
    command: ["python3", "scripts/brain/predict.py"]
    depends_on:
      - redis
    network_mode: "host"
  redis:
    image: redis
    ports:
      - 6379:6379
    network_mode: "host"
