FROM mpsamurai/neochi:raspbian-cv2

WORKDIR /tmp
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt && \
    rm requirements.txt

WORKDIR /code
COPY neochi ./neochi

COPY entrypoint.sh /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

ENV PYTHONUNBUFFERED 1

CMD ["scripts/run-all.sh"]