FROM balenalib/rpi-raspbian:stretch

COPY qemu-arm-static /usr/bin/qemu-arm-static

RUN apt-get update && \
    apt-get install -y libblas-dev liblapack-dev python3-dev \
    libatlas-base-dev gfortran python3-setuptools libhdf5-dev wget && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py

RUN wget https://www.piwheels.org/simple/tensorflow/tensorflow-1.14.0-cp35-none-linux_armv6l.whl && \
    pip3 install numpy scipy scikit-learn h5py && \
    pip3 install -U tensorflow-1.14.0-cp35-none-linux_armv6l.whl

ENV PYTHONUNBUFFERED 1