name: GITHUB_REF test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:
        run: |
          branch=${GITHUB_REF:11}
          echo ${branch////-}