name: Python package

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - test/workflow

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest