name: Python package

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - name:
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev curl
    - name: Install dependencies
      run: |
        sudo python3 -m pip uninstall pip
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3 get-pip.py
        sudo pip3 install -r requirements.txt
        sudo pip3 install opencv-python
    - name: Lint with flake8
      run: |
        sudo pip3 install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        sudo pip3 install pytest
        pytest