name: Python package

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - test/workflow

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v1
    - name:
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install opencv-python
    - name: Lint with flake8
      run: |
        pip3 install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip3 install pytest
        pytest